name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      group: shared
      labels: staging-sep-webhook-api-runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    - name: Install dependencies
      run: dotnet restore JustEat.StatsD.sln
    
    - name: Build
      run: dotnet build JustEat.StatsD.sln --configuration Release --no-restore
    
    - name: Pack
      run: dotnet pack JustEat.StatsD.sln --configuration Release --no-build --output ./JustEat.StatsD
      
    - name: Setup JFrog CLI
      uses: actions/setup-jfrog-cli@v3.1.0
      env:
        JF_URL: ${{ secrets.JFROG_URL }}
        JF_USER: ${{ secrets.JFROG_USER }}
        JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    
    - name: Upload to Artifactory
      run: |
        jf rt ping
        jf rt u "./JustEat.StatsD/JustEat.StatsD.*.nupkg" "sep-nuget/Packages/"
